
project_id = "vvtnzixsxfjzwhjetrfm"

[functions.processa-richiesta]
verify_jwt = false

[functions.storico]
verify_jwt = false

[functions.get-products]
verify_jwt = false

[functions.api-products-internal-gt45dsqt1plqkwsxcz]
verify_jwt = false

[functions.api-items]
verify_jwt = false

[functions.api-process]
verify_jwt = false

[functions.api-history]
verify_jwt = false

[functions.update-products-quantity]
verify_jwt = false

[functions.invite-capcut-pro]
verify_jwt = false

[functions.get-oauth2-token]
verify_jwt = false
